# Generated by Django 5.2.7 on 2025-10-19 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('M', 'M Series'), ('X', 'X Series'), ('I', 'i Series'), ('Z', 'Z Series'), ('OTHER', 'Other Series')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='cars/')),
                ('horsepower', models.IntegerField()),
                ('acceleration', models.DecimalField(decimal_places=1, max_digits=4)),
                ('top_speed', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('alpine_white', 'Alpine White'), ('black_sapphire', 'Black Sapphire'), ('mineral_grey', 'Mineral Grey'), ('tanzanite_blue', 'Tanzanite Blue'), ('sao_paulo_yellow', 'São Paulo Yellow')], max_length=20)),
                ('wheels', models.CharField(choices=[('standard', 'Standard 18"'), ('sport', 'Sport 19"'), ('premium', 'Premium 20"'), ('performance', 'Performance 21"')], max_length=20)),
                ('interior', models.CharField(choices=[('sensatec_black', 'Sensatec Black'), ('vernasca_cognac', 'Vernasca Cognac'), ('merino_black', 'Merino Black'), ('individual_white', 'Individual White')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
